# Technology Explorers Course 2, Lab 2: Practice with Numpy

**Instructor**: Wesley Beckner

**Contact**: wesleybeckner@gmail.com

<br>

---

<br>

In this lab we will continue to practice with pandas

<br>

---




In [1]:
import pandas as pd
import numpy as np

# Q1 

Create a 3x3 array of all True's (booleans)

In [5]:
# cell for Q1
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Q2

extract all numbers divisible by 3

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [6]:
# cell for Q2
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr%3==0) & (arr!=0)]

array([3, 6, 9])

There is a nifty tool, `np.where()`. The syntax works like `np.where(<where this condition is true> , <return elements from this array>, <otherwise return elements from this aray>)`

In [ ]:
# Ex
a = np.arange(10)
np.where(a<5, a, a*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

A similar but slightly different tool is `np.argwhere` which will return the indices of the array where the conditional is true

In [ ]:
# Ex
np.argwhere(a<5)

array([[0],
       [1],
       [2],
       [3],
       [4]])

# Q3

replace all odd numbers in `arr` with `-1` without changing `arr` (return a new array using `np.where`)

In [11]:
# cell for Q3
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr%2==0,arr,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q4

create the following array without hard coading (i.e. don't write any of the values in your coad)

```
a = np.array([1,2,3])`
# desired output:
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

Hints:

* [repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html)
* [tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [16]:
# cell for Q4
a = np.array([1,2,3])
# desired output:
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
arr1 = np.repeat(a,3)
arr2 = np.tile(a,3)
np.concatenate((arr1,arr2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Q5
get indices where elements in `a` and `b` match.

In [17]:
# cell for Q5
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.argwhere(a==b)

array([[1],
       [3],
       [5],
       [7]])

# Q6

grab numbers between 5 and 10 in `b`

In [18]:
# cell for Q6
b = np.array([7,2,10,2,7,4,9,4,9,8])
b[(b>5)&(b<10)]

array([7, 7, 9, 9, 8])

# Q7

swap columns 2 and 3 in `arr`

In [40]:
# cell for Q7
arr = np.arange(9).reshape(3,3)
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [34]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q8

compute the mean, median, and standard deviation of `sepallength`

In [26]:
# cell for Q8
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [45]:
print(sepallength.mean(), np.median(sepallength), sepallength.std())

5.843333333333334 5.8 0.8253012917851409


# Q9

normalize sepallength so that all values occur between 0 and 1

(_hint: (observation - min / (max - min))_)

In [ ]:
# cell for Q9

# Q10

calculate the 95 percentile score of `sepallength` using `np.percentile`

In [ ]:
# cell for Q10

Complete additional exercises if you wish at [machinelearningplus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)